In [14]:
import tensorflow as tf

x = tf.constant(1.0,shape=[1,3,3,1]) 
kernel = tf.Variable(tf.random_uniform([2,2,1,1]))
y = tf.nn.conv2d(x,kernel,strides=[1,1,1,1],padding='SAME')

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

print kernel.eval(session=sess)
print y.eval(session=sess)


[[[[ 0.95173991]]

  [[ 0.38284373]]]


 [[[ 0.39156973]]

  [[ 0.09101355]]]]
[[[[ 1.81716692]
   [ 1.81716692]
   [ 1.34330964]]

  [[ 1.81716692]
   [ 1.81716692]
   [ 1.34330964]]

  [[ 1.33458364]
   [ 1.33458364]
   [ 0.95173991]]]]


In [24]:
import tensorflow as tf

x = tf.constant(1.0, shape=[1,3,3,1])  
kernel = tf.constant(1.0, shape=[3,3,1,1])
output_shape = [1,6,6,1]
y = tf.nn.conv2d_transpose(x,kernel,output_shape=output_shape,strides=[1,2,2,1],padding='SAME')

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

print y.eval(session=sess)


[[[[ 1.]
   [ 1.]
   [ 2.]
   [ 1.]
   [ 2.]
   [ 1.]]

  [[ 1.]
   [ 1.]
   [ 2.]
   [ 1.]
   [ 2.]
   [ 1.]]

  [[ 2.]
   [ 2.]
   [ 4.]
   [ 2.]
   [ 4.]
   [ 2.]]

  [[ 1.]
   [ 1.]
   [ 2.]
   [ 1.]
   [ 2.]
   [ 1.]]

  [[ 2.]
   [ 2.]
   [ 4.]
   [ 2.]
   [ 4.]
   [ 2.]]

  [[ 1.]
   [ 1.]
   [ 2.]
   [ 1.]
   [ 2.]
   [ 1.]]]]


In [25]:
import tensorflow as tf
x1 = tf.constant(1.0, shape=[1,2,2,1]) 
kernel = tf.Variable(tf.random_uniform([3,3,1,1]))
output_shape = [1,4,4,1]
y3 = tf.nn.conv2d_transpose(x1,kernel,output_shape=output_shape, strides=[1,2,2,1],padding="SAME") 
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)


print kernel.eval(session=sess)
print y3.eval(session=sess)
    
    

[[[[ 0.10856032]]

  [[ 0.59885716]]

  [[ 0.2087307 ]]]


 [[[ 0.07439339]]

  [[ 0.61714029]]

  [[ 0.25675881]]]


 [[[ 0.55574286]]

  [[ 0.16554129]]

  [[ 0.11946464]]]]
[[[[ 0.10856032]
   [ 0.59885716]
   [ 0.31729102]
   [ 0.59885716]]

  [[ 0.07439339]
   [ 0.61714029]
   [ 0.3311522 ]
   [ 0.61714029]]

  [[ 0.66430318]
   [ 0.76439846]
   [ 0.99249852]
   [ 0.76439846]]

  [[ 0.07439339]
   [ 0.61714029]
   [ 0.3311522 ]
   [ 0.61714029]]]]
